self.keyboard.walk("s",4)
self.keyboard.walk("d",7.8, False)
self.keyboard.keyDown("w")
self.keyboard.keyDown("a")
time.sleep(5)
self.keyboard.keyUp("w")
self.keyboard.keyUp("a")
self.keyboard.keyDown("d")
time.sleep(3.5)
self.keyboard.press("space")
time.sleep(8)
self.keyboard.keyUp("d")
self.keyboard.keyDown("w")
time.sleep(5.5)
self.keyboard.keyUp("w")
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
time.sleep(1)
self.keyboard.press("space")
time.sleep(0.3)
self.keyboard.keyDown("w")
time.sleep(1)
self.keyboard.press("space")
time.sleep(3.5)
self.keyboard.press("space")
time.sleep(4)
self.keyboard.keyUp("w")
self.keyboard.walk("s",0.35)
self.keyboard.walk("d",2, False)
self.keyboard.walk("w",0.8)
self.keyboard.multiWalk(["s","a"], 0.9)
self.keyboard.walk("d",0.25)

    