self.keyboard.walk("a",1, False)
self.keyboard.keyDown("s")
self.keyboard.keyDown("d")
time.sleep(10)
self.keyboard.keyUp("s")
self.keyboard.keyUp("d")
self.keyboard.walk("d",2.5, False)
self.keyboard.keyDown("w")
time.sleep(7)
self.keyboard.press("space")
time.sleep(2)
self.keyboard.press("space")
time.sleep(2.5)
self.keyboard.press("space")
time.sleep(2.5)
self.keyboard.keyUp("w")
self.keyboard.walk("s",0.35)
self.keyboard.walk("d",2, False)
self.keyboard.walk("w",0.8)
self.keyboard.multiWalk(["s","a"], 0.9)
self.keyboard.walk("d",0.25)