for _ in range(10):
    self.keyboard.press("a", 0.25)
    self.keyboard.press("s", 0.75)
self.keyboard.slowPress(".")
self.keyboard.walk("w",30)
self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.walk("w",12)
self.keyboard.slowPress(".")
self.keyboard.walk("s",0.6)
self.keyboard.walk("d",4)
self.keyboard.walk("w",1)
self.keyboard.walk("s",0.6)
