self.keyboard.walk("s",4)
self.keyboard.walk("d",5)
self.keyboard.walk("w",4)
self.keyboard.walk("a",8)
self.keyboard.walk("s",6)
self.keyboard.walk("d",3)
self.keyboard.walk("w",11, False)
self.keyboard.walk("s",0.15)
self.keyboard.walk("d",0.35)
self.keyboard.walk("w",4)
self.keyboard.walk("s",0.35)
self.keyboard.walk("d",4)
self.keyboard.walk("s",0.6)
    
