self.keyboard.walk("w",1)
self.keyboard.keyDown("s")
sleep(0.2)
self.keyboard.keyUp("s")
self.keyboard.walk("a",1.5)
self.keyboard.walk("d",1.78)
self.keyboard.walk("w",0.1)
self.keyboard.walk("a",1.70)