move.press(",")
move.press("e")
pag.keyDown("w")
time.sleep(0.1)
move.press("space")
move.press("space")
time.sleep(3.2)
pag.keyUp("w")
move.press("space")
time.sleep(0.5)
move.hold("w",1.8)
move.press(".")
move.press(".")
move.hold("w",1.8)
    
