move.press(",")
move.press(",")
move.press("e")
pag.keyDown("w")
time.sleep(0.35)
move.press("space")
move.press("space")
time.sleep(2.81)
move.press(",")
move.press(",")
time.sleep(1.35)
pag.keyUp("w")
move.press("space")
time.sleep(0.7)
    
