self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.slowPress("e")
self.keyboard.keyDown("w")
sleep(0.4)
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
sleep(0.5)
self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.slowPress(".")
self.keyboard.slowPress(".")
sleep(0.2)
self.keyboard.keyUp("w")
self.keyboard.slowPress("space")
time.sleep(1)
if self.isBesideE(["talk", "polar"]):
    self.keyboard.keyDown("w")
    time.sleep(1)
    self.keyboard.press("space")
    time.sleep(1.5)
    self.keyboard.keyUp("w")

    
