self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.slowPress("e")
self.keyboard.keyDown("w")
time.sleep(0.35)
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
time.sleep(2.81)
self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
time.sleep(1.35)
self.keyboard.keyUp("w")
self.keyboard.slowPress("space")
time.sleep(0.7)
    
