self.keyboard.press(",")
self.keyboard.slowPress("e")
time.sleep(0.95)
self.keyboard.keyDown("w")
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
time.sleep(8)
self.keyboard.keyUp("w")
self.keyboard.slowPress("space")
time.sleep(0.8)
self.keyboard.walk("w",0.2)
self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.walk("w",2.4, False)
self.keyboard.press(",")
self.keyboard.press(",")
