#Ahk code converted by Existance Macro


#auryn gathering path
auryndelay=175
for i in range(width):
	#infinity
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*3*1.4)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*3*1.4)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(afclrkey, False)
	#big circle
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(afclrkey, False)
	#flip!!
	#move to other side (half circle)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyUp(afcfbkey, False)
	#pause here
	sleep(0.05)
	#reverse infinity
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*3*1.4)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*1.4)
	self.keyboard.keyUp(tclrkey, False)
	#big circle
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(tclrkey, False)
	#flip!!
	#move to other side (half circle)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(auryndelay*9/2000*size*i*1.1*2*1.4)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyUp(tcfbkey, False)
