#Ahk code converted by Existance Macro


for i in range(width):
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(4 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(2 * size)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(2 * size)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(math.sqrt( ( ( 8 * size ) ** 2 ) + ( ( 8 * size ) ** 2 )))
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(2 * size)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(6.7 * size)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(2 * size)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(2 * size)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(2 * size)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(3 * size)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(8 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(math.sqrt( ( ( 4 * size ) ** 2 ) + ( ( 4 * size ) ** 2 )))
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyUp(afclrkey, False)
