for i in range(width):
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(1.25 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(7 * size, 10)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(1.25 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(6.66 * size, 10)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(1.25 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(7 * size, 10)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(2 * size)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(6.5 * size, 10)
	self.keyboard.keyUp(afcfbkey, False)
for i in range(width):
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(1.25 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(7 * size, 10)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(1 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(6.66 * size, 10)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(1.25 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(7 * size, 10)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(1.25 * size)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(6.5 * size, 10)
	self.keyboard.keyUp(afcfbkey, False)